### ISSUE TITLE
ImportError: No module named parse (Plone 5.2.2)

### ISSUE THREAD

**Issue by registroforzado** [jazkarta/jazkarta.shop#64]
Is there a way to solve this? Thank you

$ bin/client1 fg
/home/plone/5/buildout-cache/eggs/Products.GenericSetup-2.0.2-py2.7.egg/Products/GenericSetup/registry.py:16: ImportWarning: Not importing directory '/home/plone/5/buildout-cache/eggs/Products.GenericSetup-2.0.2-py2.7.egg/Products/GenericSetup/xml': missing __init__.py
  from xml.sax import parseString
2020-10-18 01:57:18,169 WARNING [Init:89][MainThread] Class Products.CMFFormController.ControllerPythonScript.ControllerPythonScript has a security declaration for nonexistent method 'ZPythonScriptHTML_changePrefs'
2020-10-18 01:57:18,175 WARNING [Init:89][MainThread] Class Products.CMFFormController.ControllerValidator.ControllerValidator has a security declaration for nonexistent method 'ZPythonScriptHTML_changePrefs'
/home/plone/5/buildout-cache/eggs/Products.CMFPlacefulWorkflow-2.0.2-py2.7.egg/Products/CMFPlacefulWorkflow/permissions.py:5: DeprecationWarning: setDefaultRoles is deprecated. Please use addPermission from AccessControl.Permission.
  from Products.CMFCore.permissions import setDefaultRoles
2020-10-18 01:57:18,653 INFO    [Products.PloneHotfix20200121:49][MainThread] Applied sql_quote patch
2020-10-18 01:57:18,717 INFO    [Products.PloneHotfix20200121:49][MainThread] Applied in_portal patch
2020-10-18 01:57:18,718 INFO    [Products.PloneHotfix20200121:49][MainThread] Applied password_validation patch
2020-10-18 01:57:18,729 INFO    [Products.PloneHotfix20200121:49][MainThread] Applied pac patch
/home/plone/5/buildout-cache/eggs/Products.PloneHotfix20200121-1.1-py2.7.egg/Products/PloneHotfix20200121/utils.py:4: DeprecationWarning: getSiteEncoding: `getSiteEncoding` is deprecated. Plone only supports UTF-8 currently. This method always returns "utf-8"
  from Products.CMFPlone.utils import *
2020-10-18 01:57:18,745 INFO    [Products.PloneHotfix20200121:49][MainThread] Applied content patch
2020-10-18 01:57:18,750 INFO    [Products.PloneHotfix20200121:49][MainThread] Applied layout patch
/home/plone/5/buildout-cache/eggs/PyJWT-1.7.1-py2.7.egg/jwt/utils.py:8: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography.hazmat.primitives.asymmetric.utils import (
2020-10-18 01:57:18,840 INFO    [Products.PloneHotfix20200121:49][MainThread] Applied restapi_local_roles patch
2020-10-18 01:57:18,841 INFO    [Products.PloneHotfix20200121:57][MainThread] Hotfix installed
/home/plone/5/buildout-cache/eggs/Products.PortalTransforms-3.1.8-py2.7.egg/Products/PortalTransforms/transforms/text_to_html.py:2: DeprecationWarning: html_quote is deprecated. Please import from DocumentTemplate.html_quote. These shims will go away in DocumentTemplate 4.0.
  from DocumentTemplate.DT_Util import html_quote
2020-10-18 01:57:18,990 INFO    [ZEO.ClientStorage:209][MainThread] zeostorage ClientStorage (pid=25384) created RW/normal for storage: '1'
2020-10-18 01:57:18,991 INFO    [ZEO.cache:208][MainThread] created temporary cache file '<fdopen>'
2020-10-18 01:57:18,998 INFO    [ZEO.asyncio.base:51][zeostorage zeo client networking thread] Connected Protocol((u'127.0.0.1', 8522), '1', False)
2020-10-18 01:57:18,999 INFO    [ZEO.ClientStorage:366][zeostorage zeo client networking thread] zeostorage Connected to storage: ('localhost.localdomain', 8522)
2020-10-18 01:57:19,002 WARNING [TemporaryStorage:93][MainThread] DEPRECATED: Usage of the package tempstorage is deprecated, as it is known to randomly lose data.
Especially on Zope 4. For details see https://github.com/zopefoundation/tempstorage/issues/8
and https://github.com/zopefoundation/tempstorage

/home/plone/5/buildout-cache/eggs/tempstorage-5.1-py2.7.egg/tempstorage/TemporaryStorage.py:94: DeprecationWarning: DEPRECATED: Usage of the package tempstorage is deprecated, as it is known to randomly lose data.
Especially on Zope 4. For details see https://github.com/zopefoundation/tempstorage/issues/8
and https://github.com/zopefoundation/tempstorage

  warnings.warn(deprecation_warning, DeprecationWarning)
2020-10-18 01:57:19,003 INFO    [ZEO.ClientStorage:209][MainThread] sitio_plone5 ClientStorage (pid=25384) created RW/normal for storage: 'sitio_plone5'
2020-10-18 01:57:19,004 INFO    [ZEO.cache:208][MainThread] created temporary cache file '<fdopen>'
2020-10-18 01:57:19,005 INFO    [ZEO.asyncio.base:51][sitio_plone5 zeo client networking thread] Connected Protocol((u'127.0.0.1', 8522), 'sitio_plone5', False)
2020-10-18 01:57:19,006 INFO    [ZEO.ClientStorage:366][sitio_plone5 zeo client networking thread] sitio_plone5 Connected to storage: ('localhost.localdomain', 8522)
2020-10-18 01:57:19,009 INFO    [ZEO.ClientStorage:209][MainThread] sitio_plone5tiendas ClientStorage (pid=25384) created RW/normal for storage: 'sitio_plone5tiendas'
2020-10-18 01:57:19,009 INFO    [ZEO.cache:208][MainThread] created temporary cache file '<fdopen>'
2020-10-18 01:57:19,011 INFO    [ZEO.asyncio.base:51][sitio_plone5tiendas zeo client networking thread] Connected Protocol((u'127.0.0.1', 8522), 'sitio_plone5tiendas', False)
2020-10-18 01:57:19,011 INFO    [ZEO.ClientStorage:366][sitio_plone5tiendas zeo client networking thread] sitio_plone5tiendas Connected to storage: ('localhost.localdomain', 8522)
2020-10-18 01:57:19,014 INFO    [ZEO.ClientStorage:209][MainThread] sitio_plone5lineage ClientStorage (pid=25384) created RW/normal for storage: 'sitio_plone5lineage'
2020-10-18 01:57:19,014 INFO    [ZEO.cache:208][MainThread] created temporary cache file '<fdopen>'
2020-10-18 01:57:19,016 INFO    [ZEO.asyncio.base:51][sitio_plone5lineage zeo client networking thread] Connected Protocol((u'127.0.0.1', 8522), 'sitio_plone5lineage', False)
2020-10-18 01:57:19,016 INFO    [ZEO.ClientStorage:366][sitio_plone5lineage zeo client networking thread] sitio_plone5lineage Connected to storage: ('localhost.localdomain', 8522)
/home/plone/5/buildout-cache/eggs/plone.app.textfield-1.3.4-py2.7.egg/plone/app/textfield/utils.py:10: DeprecationWarning: ComponentLookupError is deprecated. Import from zope.interface.interfaces
  from zope.component.interfaces import ComponentLookupError
/home/plone/5/buildout-cache/eggs/plone.app.upgrade-2.0.34-py2.7.egg/plone/app/upgrade/__init__.py:167: DeprecationWarning: LockItem is deprecated. Please import from OFS.LockItem.
  from webdav.LockItem import LockItem
/home/plone/5/buildout-cache/eggs/plone.subrequest-1.9.2-py2.7.egg/plone/subrequest/__init__.py:18: DeprecationWarning: zope.site.hooks has moved to zope.component.hooks. Import of zope.site.hooks will become unsupported in Version 5.0
  from zope.site.hooks import getSite
/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py:241: DeprecationWarning: IObjectEvent is deprecated. Import from zope.interface.interfaces
  obj = getattr(mod, oname)
/home/plone/5/buildout-cache/eggs/plone.app.content-3.8.6-py2.7.egg/plone/app/content/browser/vocabulary.py:10: DeprecationWarning: IFieldPermissionChecker is deprecated. Import IFieldPermissionChecker from plone.app.z3cform.interfaces instead
  from plone.app.widgets.interfaces import IFieldPermissionChecker
2020-10-18 01:57:20,042 INFO    [chameleon.config:38][MainThread] directory cache: /home/plone/5/zeocluster/var/cache.
/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py:241: DeprecationWarning: IComponentRegistry is deprecated. Import from zope.interface.interfaces
  obj = getattr(mod, oname)
/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py:241: DeprecationWarning: LockableItem is deprecated. Please import from OFS.Lockable.
  obj = getattr(mod, oname)
/home/plone/5/buildout-cache/eggs/plone.schemaeditor-3.0.1-py2.7.egg/plone/schemaeditor/utils.py:6: DeprecationWarning: ObjectEvent is deprecated. Import from zope.interface.interfaces
  from zope.component.interfaces import ObjectEvent
/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py:241: DeprecationWarning: LazyMap is deprecated. Please import from ZTUtils.Lazy.
  obj = getattr(mod, oname)
/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py:241: DeprecationWarning: LazyCat is deprecated. Please import from ZTUtils.Lazy.
  obj = getattr(mod, oname)
/home/plone/5/buildout-cache/eggs/plone.app.upgrade-2.0.34-py2.7.egg/plone/app/upgrade/v50/betas.py:8: DeprecationWarning: ILanguageSchema is deprecated. It has been moved to plone.i18n.interfaces, import from there instead.
  from Products.CMFPlone.interfaces import ILanguageSchema
/home/plone/5/buildout-cache/eggs/Products.PluggableAuthService-2.4-py2.7.egg/Products/PluggableAuthService/plugins/exportimport.py:19: ImportWarning: Not importing directory '/home/plone/5/buildout-cache/eggs/Products.PluggableAuthService-2.4-py2.7.egg/Products/PluggableAuthService/plugins/xml': missing __init__.py
  from xml.dom.minidom import parseString
Traceback (most recent call last):
  File "/home/plone/5/zeocluster/parts/client1/bin/interpreter", line 311, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "/home/plone/5/buildout-cache/eggs/Zope-4.5.1-py2.7.egg/Zope2/Startup/serve.py", line 255, in <module>
    sys.exit(main() or 0)
  File "/home/plone/5/buildout-cache/eggs/Zope-4.5.1-py2.7.egg/Zope2/Startup/serve.py", line 251, in main
    return command.run()
  File "/home/plone/5/buildout-cache/eggs/Zope-4.5.1-py2.7.egg/Zope2/Startup/serve.py", line 190, in run
    global_conf=vars)
  File "/home/plone/5/buildout-cache/eggs/Zope-4.5.1-py2.7.egg/Zope2/Startup/serve.py", line 220, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "/home/plone/5/buildout-cache/eggs/PasteDeploy-2.1.0-py2.7.egg/paste/deploy/loadwsgi.py", line 253, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/plone/5/buildout-cache/eggs/PasteDeploy-2.1.0-py2.7.egg/paste/deploy/loadwsgi.py", line 278, in loadobj
    return context.create()
  File "/home/plone/5/buildout-cache/eggs/PasteDeploy-2.1.0-py2.7.egg/paste/deploy/loadwsgi.py", line 715, in create
    return self.object_type.invoke(self)
  File "/home/plone/5/buildout-cache/eggs/PasteDeploy-2.1.0-py2.7.egg/paste/deploy/loadwsgi.py", line 209, in invoke
    app = context.app_context.create()
  File "/home/plone/5/buildout-cache/eggs/PasteDeploy-2.1.0-py2.7.egg/paste/deploy/loadwsgi.py", line 715, in create
    return self.object_type.invoke(self)
  File "/home/plone/5/buildout-cache/eggs/PasteDeploy-2.1.0-py2.7.egg/paste/deploy/loadwsgi.py", line 152, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/home/plone/5/buildout-cache/eggs/PasteDeploy-2.1.0-py2.7.egg/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/plone/5/buildout-cache/eggs/Zope-4.5.1-py2.7.egg/Zope2/Startup/run.py", line 71, in make_wsgi_app
    starter.prepare()
  File "/home/plone/5/buildout-cache/eggs/Zope-4.5.1-py2.7.egg/Zope2/Startup/starter.py", line 41, in prepare
    self.startZope()
  File "/home/plone/5/buildout-cache/eggs/Zope-4.5.1-py2.7.egg/Zope2/Startup/starter.py", line 99, in startZope
    Zope2.startup_wsgi()
  File "/home/plone/5/buildout-cache/eggs/Zope-4.5.1-py2.7.egg/Zope2/__init__.py", line 50, in startup_wsgi
    _startup()
  File "/home/plone/5/buildout-cache/eggs/Zope-4.5.1-py2.7.egg/Zope2/App/startup.py", line 143, in startup
    load_zcml()
  File "/home/plone/5/buildout-cache/eggs/Zope-4.5.1-py2.7.egg/Zope2/App/startup.py", line 58, in load_zcml
    load_site()
  File "/home/plone/5/buildout-cache/eggs/Zope-4.5.1-py2.7.egg/Zope2/App/zcml.py", line 45, in load_site
    _context = xmlconfig.file(site_zcml)
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 657, in file
    include(context, name, package)
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 365, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 704, in end
    self.stack.pop().finish()
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 869, in finish
    actions = self.handler(context, **args)
  File "/home/plone/5/buildout-cache/eggs/Zope-4.5.1-py2.7.egg/OFS/metaconfigure.py", line 47, in loadProducts
    xmlconfig.include(_context, zcml, package=product)
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 365, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 704, in end
    self.stack.pop().finish()
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 869, in finish
    actions = self.handler(context, **args)
  File "/home/plone/5/buildout-cache/eggs/z3c.autoinclude-0.4.0-py2.7.egg/z3c/autoinclude/zcml.py", line 122, in includePluginsDirective
    includeZCMLGroup(_context, info, filename)
  File "/home/plone/5/buildout-cache/eggs/z3c.autoinclude-0.4.0-py2.7.egg/z3c/autoinclude/zcml.py", line 37, in includeZCMLGroup
    include(_context, filename, includable_package)
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 365, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 704, in end
    self.stack.pop().finish()
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 869, in finish
    actions = self.handler(context, **args)
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 365, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 235, in _handle_exception
    reraise(exc, None, sys.exc_info()[2])
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 704, in end
    self.stack.pop().finish()
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 868, in finish
    args = toargs(context, *self.argdata)
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 1687, in toargs
    args[str(name)] = field.fromUnicode(s)
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/fields.py", line 172, in fromUnicode
    value = self.context.resolve(name)
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 226, in resolve
    __import__(mname)
  File "/home/plone/5/zeocluster/src/jazkarta.shop/jazkarta/shop/browser/shipping.py", line 20, in <module>
    from .checkout import P5Mixin
  File "/home/plone/5/zeocluster/src/jazkarta.shop/jazkarta/shop/browser/checkout/__init__.py", line 3, in <module>
    from premailer import Premailer
  File "/home/plone/5/buildout-cache/eggs/premailer-3.7.0-py2.7.egg/premailer/__init__.py", line 1, in <module>
    from .premailer import Premailer, transform  # noqa
  File "/home/plone/5/buildout-cache/eggs/premailer-3.7.0-py2.7.egg/premailer/premailer.py", line 7, in <module>
    from urllib.parse import urljoin, urlparse
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/home/plone/5/zeocluster/src/jazkarta.shop/jazkarta/shop/browser/configure.zcml", line 18.2-25.6
    File "/home/plone/5/zeocluster/parts/client1/etc/site.zcml", line 16.2-16.23
    File "/home/plone/5/buildout-cache/eggs/Products.CMFPlone-5.2.2-py2.7.egg/Products/CMFPlone/configure.zcml", line 110.2-114.8
    File "/home/plone/5/zeocluster/src/jazkarta.shop/jazkarta/shop/configure.zcml", line 34.2-34.32
    ImportError: No module named parse

**Comment by cguardia** [comment]
Sorry for the late response. This is because the latest premailer package does not support Python 2.7 anymore. The buildout installation instructions that we added to the README fix this.
